services:
  api:
    build: .
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:17-alpine
    env_file: .env
    volumes:
      - taskdata:/var/lib/postgresql/data

volumes:
  taskdata:
